name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      working-directory: ./Vengeance/src
      run: make
    - name: make check
      working-directory: ./Vengeance/src
      run: make check
    - name: make distcheck
      working-directory: ./Vengeance/src
      run: make distcheck
